version: '2'
services:
    project-app:
        image: project
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://project-postgresql:5432/project
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://project-elasticsearch:9200
        ports:
            - 8080:8080
    project-postgresql:
        extends:
            file: postgresql.yml
            service: project-postgresql
    project-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: project-elasticsearch
